### PR TITLE
Mongo mongo

### PR DESCRIPTION
**Pull request by elinaarenstrup**
This was a fun and challenging project. I'm not sure I really get how everything works, but I'm getting there :)

### CODE REVIEW

**Comment by elinaarenstrup** [comment]
> Good job Elin! On your deployed site I can only see the '/' endpoint though and not the `/shows` or `/shows/:show_id`. Maybe it worked when you first deployed, but take another look at heroku (make sure the `MONGO_URL` and `RESET_DB` config vars are set up correctly etc. You can also check heroku's logs. Keep up the good work!

Thanks Matilda! 💜 I checked the vars at and they seem to be right. When I visit the deployed site I can see all the endpoints. Where do I find the logs on Heroku and what should I look for ? 🤔

**Comment by HIPPIEKICK** [comment]
> > Good job Elin! On your deployed site I can only see the '/' endpoint though and not the `/shows` or `/shows/:show_id`. Maybe it worked when you first deployed, but take another look at heroku (make sure the `MONGO_URL` and `RESET_DB` config vars are set up correctly etc. You can also check heroku's logs. Keep up the good work!
> 
> Thanks Matilda! 💜 I checked the vars at and they seem to be right. When I visit the deployed site I can see all the endpoints. Where do I find the logs on Heroku and what should I look for ? 🤔

Hmm, that's odd! Is this the right URL: [https://mongo-api-poject.herokuapp.com/](https://mongo-api-poject.herokuapp.com/)? If yes - does it work on your phone as well? Heroku logs: go in to your application in heroku, and in the top right corner, click "More" and then "View logs". When I check your `/shows` endpoint I get Application Error and in the console a 503 error 🤔

**Comment by elinaarenstrup** [comment]
It's me again :D For some reason there was - in the username that wasn't supposed to be there. Maybe that could solve it? Works on my phone now :D The link is correct (poject is a word right? lol)

 https://mongo-api-poject.herokuapp.com/

**Comment by HIPPIEKICK** [comment]
> It's me again :D For some reason there was " - " in the username that wasn't supposed to be there. I removed them, maybe that could have been the problem? Works on my phone now :D The link is correct (poject is a word right? lol)
> 
> https://mongo-api-poject.herokuapp.com/

Works for me too! 💯

**Pull request closed without merging**
